export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const SET_ALL_ITEMS = 'SET_ALL_ITEMS';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';

export const ITEMS_LOADING_STATUS = 'ITEMS_LOADING_STATUS';